name: Continuous Delivery
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  push:
    branches:
      - main

#tarefa de deliver
jobs:
  delivery:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Simulando CD
        uses: actions/upload-artifact@v4
        with:
          name: projetozipado.zip
          path: |
            main.py
            README.md

#tarefa de deploy

  deploy:
    runs-on: ubuntu-latest
    needs: delivery
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: projetozipado.zip
      - name: Display structure of downloaded files
        run: ls -R

#integrando ao docker
  docker:
      needs: delivery
      runs-on: ubuntu-latest
      steps:
         -
           name: Checkout
           uses: actions/checkout@v4
         -
           name: Set up QEMU
           uses: docker/setup-qemu-action@v3
         -
           name: Login to Docker Hub
           uses: docker/login-action@v3
           with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

         - name: Build and pushl
           uses: docker/build-push-action@v6
           with:
              push: true
              tags: cellarius2/imagem-aula:latest